version: '3.5'
services:
  oraculo:
    build: .
    volumes:
      - .:/oraculo
    ports:
    - "4000:4000"
    command: ["./run.sh"]
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:10